### ISSUE TITLE
version.json in the bundle

### ISSUE THREAD

**Issue by determinator** [mathieudutour/cordova-plugin-hotpushes#12]
Hello,

I'm trying to integrate this plugin in my cordova project but with no success as for now. The server part looks clear and following the examples I did it. It's not clear, however, what should be the content of version.json in the application bundle. Initially, I put the same file as on the server (certainly this is not the idea). The file is in www directory i.e. where index.html is and then:

TypeError: Cannot read property '_getLocalVersion' of undefined ...
at file:///android_asset/www/plugins/cordova-plugin-hotpushes/www/index.js:570:9
at HotPush.loadLocalFiles (file:///android_asset/www/plugins/cordova-plugin-hotpushes/www/index.js:569:10)

Is there any information about version.json in the app bundle?
Could we have a sample project with the plugin setup and working as someone else already asked? That would certainly help anybody exploring this plugin.

Thanks.

**Comment by pablomaurer** [comment]
You may also look at [cordova-hot-code-push](https://github.com/nordnet/cordova-hot-code-push).

**Comment by determinator** [comment]
thank you for your answer, mnewmedia. But my focus is windows app as for now and I saw your link does not mention it works for windows while this project here eventually does.
